### ISSUE TITLE
Batch API / support HTTP pipelines

### ISSUE THREAD

**Issue by sirupsen** [Shopify/toxiproxy#102] opened 2016-04-18 19:02 UTC
@BlakeMesdag mentioned that creating proxies at boot of our application actually takes a while, up to 2 seconds. We can make this better. Toxiproxy should not take more than 100ms at boot, and preferably less.

The simplest thing would probably be to support HTTP pipelines / persistent connections, so we can just send a bunch of data. We may also just be doing something stupid in the Rails gem. I'd prefer that to a new API. Another possibility is that the `#populate` call becomes a native thing in Toxiproxy that just sends it a JSON dictionary of all the proxies it expects (and resets all of them).

@xthexder @jpittis

**Comment by xthexder** [comment] 2016-04-18 19:09
A `/populate` endpoint wouldn't be a bad thing to implement. It would easily be able take advantage of concurrent proxy creation (which is currently only possible with parallel requests).
Maybe something for a 2.1 release?

I noticed @BlakeMesdag already started a branch, is there any performance improvement with that?

**Comment by BlakeMesdag** [comment] 2016-04-18 19:56
@xthexder the branch is just switching from manually creating new requests and passing them to the connection, to using the connection's instance methods for those requests.

**Comment by Sirupsen** [comment] 2016-05-11 11:52
\cc @jpittis this might be something you'd be interested in

**Comment by jpittis** [comment] 2016-06-14 21:53
FYI That I've started working on a populate fix.

**Comment by Sirupsen** [comment] 2016-09-02 16:47
@xthexder are you interested in taking this up? @jpittis did work in #111 to add a populate endpoint, but it seems the problem is not with performance of all the network roundtrips (although I do feel we should have `/populate` anyway) but a performance problem inside of Toxiproxy.

**Comment by xthexder** [comment] 2016-09-02 17:27
Yeah I can take a look at this and do some benchmarks to see what the problem is.

**Comment by xthexder** [comment] 2016-12-07 20:49
Should be fixed with the Toxiproxy 2.1.0 release.

**Closed by xthexder** 2016-12-07 20:49 UTC
